config/routes.rb
Rails.application.routes.draw do
  root 'pages#index', as: 'root'
  get '/home', to: redirect('/')
  # get '/about' => 'pages#about', as: 'about'
  # get 'pages/:id' => 'pages#about'
  #get 'gallery/:id' => 'gallery#show'

  scope path: '/', controller: :pages do
  	get 'about' => :about
  	get 'test' => :test
  	get 'about/:id' => :about
  end
  get '/gallery' => 'galleries#home', as: 'gallery_home'
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base

end

app/models/page.rb
class Page < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
	def home
	end
	def show
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end
	def about
		
	end
	def test
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/galleries/home.html.erb
<div class="row">
	<div class="large-12-columns text-center">
		<!-- SOme logo soon -->
		<h2>Soon gallery of my drawings!</h2>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "My Site", root_path%></h1>
    </li>

    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"><%= link_to "Gallery", gallery_home_path%></li>
      <li><a href="#">Otro link</a></li>
      <li class="has-dropdown">
        <a href="#">Right Button Dropdown</a>
        <ul class="dropdown">
          <li><a href="#">First link in dropdown</a></li>
          <li class="active"><a href="#">Active link in dropdown</a></li>
        </ul>
      </li>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <li><%=link_to "About me", about_path%></li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailswayNew</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<%= render 'layouts/navigation' %>
	</header>
	<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<div class="row">
	<div class="small-6 large-12 columns">
		<h2>This is about me!</h2>
		<p>Segment key = </p><%= @segment_key %></p>
	</div>
</div>

app/views/pages/index.html.erb
<div class="row">
	<div class="large-12-columns text-center">
		<h2>Main page</h2>
		<p><%= link_to "This is about the page", about_path %></p>
		<p><%= link_to "Testo", test_path %></p>
	</div>
</div>